### PR TITLE
Create galaxy-bioblend container

### PR DESCRIPTION
**Pull request by anilthanki**

### CODE REVIEW

**Comment by pcm32** [comment]
didn't this require pyaml as well? Or if this is a dependency of bioblend, I'm surprised it is not in the biocontainers container.

**Comment by pcm32** [comment]
and possibly some library to connect to S3?

**Comment by pcm32** [comment]
On the container tag, I would suggest following the main package version (ie bioblend).

**Review by pcm32 — APPROVED** [review]
If these are all the dependencies that you need, then it should be fine. I would suggest using 1.1.1 as version of the container (you can alway increases patch version for newer container versions of the same package).

**Comment by pcm32** [comment]
Remember [this](https://github.com/ebi-gene-expression-group/atlas-containers?tab=readme-ov-file#very-important-for-new-containers-before-merging) before merging.

**Comment by anilthanki** [comment]
> didn't this require pyaml as well? Or if this is a dependency of bioblend, I'm surprised it is not in the biocontainers container.

When I tried locally `Yaml` got installed as dependency, as it should but suddenly it started missing from our original setup in PS
```
  yaml               conda-forge/osx-arm64::yaml-0.2.5-h3422bc3_2
```

**Comment by anilthanki** [comment]
> and possibly some library to connect to S3?

On Jenkins it gives following error

```
package bioblend-0.14.0-py_0 requires boto >=2.9.7, but none of the providers can be installed
```

but when trying locally (on ARM chip) it can be installed without any issue

```
boto3              conda-forge/noarch::boto3-1.34.100-pyhd8ed1ab_0
```

**Pull request merged**
