### PR TITLE
Add atlas-analysis-base

### PR DESCRIPTION
**Pull request by pinin4fjords**
Adding a container for dependencies of the newly separated atlas-analysis.

- [x] Add environment file and image name/tag
- [x] Create quay.io repo
- [x] Make sure robot has write on the quay.io repo.

### CODE REVIEW

**Comment by pcm32** [comment]
Shouldn't we name this atlas-analysis-base if we are not going to add the scripts in there?

**Comment by pinin4fjords** [comment]
> Shouldn't we name this atlas-analysis-base if we are not going to add the scripts in there?

Good plan!

**Review by pcm32 — APPROVED** [review]
LGTM

**Comment by pinin4fjords** [comment]
Thanks @pcm32

**Pull request merged**
